services:
  home:
    container_name: home
    build: ./home
    networks:
      - site
    ports:
       - "3027:3027"
    healthcheck:
      test:  ["CMD", "curl", "-f", "http://home:3027"]
      interval: 10s
      timeout: 1s

    depends_on:
        redis:
            condition: healthy
networks:
  site:
    external: true

