version: "3.8"

services:
  home:
    build: ./home
    volumes:
      - /etc/letsencrypt/live/kelseywilliams.co:/etc/ssl/certs
    networks:
      - site
    ports:
       - "3000:3000"
    healthcheck:
      test:  ["CMD", "curl", "-f", "https://home:8000"]
      interval: 10s
      timeout: 1s

networks:
  site:
    external: true

